server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  profiles:
    active:
      - dev
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 600
      connection-timeout: 30000
      max-lifetime: 1800000
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch.matching-strategy: ANT_PATH_MATCHER
    jpa:
      defer-datasource-initialization: true
security:
  basic-auth:
    user: safeuser
    password: 811b4516a5919cd73be3b8d63820b34007cecfb3